"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ryanwill679 (https://sketchfab.com/Ryanwill679)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/akira-bike-a5b1dc49808b40a9b94f9a4a3073d548
Title: Akira Bike
*/

import React, { useRef } from "react";
import { useGLTF, Center } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Ignition() {
    const pivot = useRef();
    const { nodes, materials } = useGLTF("/scene-optimized.glb");

    useFrame((_, delta) => {
        if (pivot.current) {
            pivot.current.rotation.y += delta * 0.6; // velocity of rotation (0.6 radians per second)
        }
    });

    return (
        <group ref={pivot}>
            <Center>
                <group scale={1}>
                    <mesh
                        geometry={nodes.Wheel__Akira_Bike_wheel__0.geometry}
                        material={materials.Akira_Bike_wheel}
                    />
                    <mesh
                        geometry={nodes.Wheel__Akira__0.geometry}
                        material={materials.Akira}
                    />
                    <mesh
                        geometry={nodes.Wheel__Material_0.geometry}
                        material={materials.Material}
                    />
                    <mesh
                        geometry={nodes.Wheel__Akira_Bike_pc_0.geometry}
                        material={materials.Akira_Bike_pc}
                    />
                    <mesh
                        geometry={nodes.Wheel__Material004_0.geometry}
                        material={materials["Material.004"]}
                    />
                    <mesh
                        geometry={nodes.Wheel__Material001_0.geometry}
                        material={materials["Material.001"]}
                    />
                    <mesh
                        geometry={nodes.Wheel__Akira_Bike_wheel_part_0.geometry}
                        material={materials.Akira_Bike_wheel_part}
                    />
                    <mesh
                        geometry={nodes.Wheel__Material003_0.geometry}
                        material={materials["Material.003"]}
                    />
                    <mesh
                        geometry={nodes.Wheel__Back_of_the_bike_001_0.geometry}
                        material={materials["Back_of_the_bike_.001"]}
                    />
                    <mesh
                        geometry={nodes.Wheel__cable__0.geometry}
                        material={materials.cable}
                    />
                    <mesh
                        geometry={nodes.Wheel__Map_1_0.geometry}
                        material={materials.Map_1}
                    />
                    <mesh
                        geometry={nodes.Wheel__pc_0.geometry}
                        material={materials.material}
                    />
                    <mesh
                        geometry={nodes.Wheel__Back_of_the_bike__0.geometry}
                        material={materials.Back_of_the_bike}
                    />
                    <mesh
                        geometry={nodes.Wheel__Glass_0.geometry}
                        material={materials.Glass}
                    />
                    <mesh
                        geometry={nodes.Wheel__S_1001_0.geometry}
                        material={materials["S_1.001"]}
                    />
                </group>
            </Center>
        </group>
    );
}

useGLTF.preload("/scene-optimized.glb");
